neovim_version: stable
neovim_repo_url: "https://github.com/Nealium104/neovim-config.git"

node_major_version: 24.x

dotfiles_dir: "{{ lookup('env', 'HOME') }}/dotfiles"

packages:
  - build-essential
  - git # install.sh duplication
  - stow
  - ripgrep
  - fd-find
  - fzf
  - tmux
  - unzip
  - jq

stow_packages:
  - tmux
  - scripts
